# Local configuration

# Experiments to run
# experiments: ['local/experiments/pretraining/rnn_all_features_pretrained.yml']
experiments: ['local/experiments/rerun/rnn_pretraining_rerun_206_1977.yml']
# experiments: ['local/experiments/rerun/rnn_rerun_a549.yml']

model: 'rnn'

# Persistence of models
persistence:
  model: true

plots:
  seq_output: false
  seq_output_ignore_neurons: ~
  seq_output_select_neurons: [66,78] # [51,100,137]
  seq_output_layer_idx: 1
  seq_output_smiles: [
  'BrC1=CC2(CCNC3=C2C(=O)c4cccnc4C3=O)C=C(Br)C1=O'
  #'Brc1ccc2c3ccc(Br)cc3C4(c5cc(Br)ccc5c6ccc(Br)cc46)c2c1'
  ]
