# Local configuration

# Experiments to run
experiments: ['local/experiments/wide_features_valid/rnn_wide_features_learning_curve.yml']

model: 'rnn'

# Persistence of models
persistence:
  model: false
