# Local configuration

# Experiments to run

experiments: ['local/experiments/rerun/rnn_pretraining_rerun_206_1977.yml']
model: 'rnn'

# Persistence of models
persistence:
  model: true

plots:
  print_train_test_pred: false
  print_train_test_pred_cnt: 15