# Local configuration

# Experiments to run
experiments: ['local/experiments/test/rnn_test.yml']

# Database
db:
  user: 'guest'
  pass: 'relational'
  host: 'relational.fit.cvut.cz'
  name: 'ctu_qsar'
  driver: 'mysql'

# Statistics
statistics:
  table: 'journal'
