# Local configuration

# Experiments to run
experiments: ['local/experiments/visualization/rnn_visual_fasta_seq.yml']
model: 'rnn'

# Persistence of models
persistence:
  model: false

plots:
  seq_output: true

  seq_output_ignore_neurons: ~
  seq_output_select_neurons: ~
  seq_output_name: 'seq_output.png'
  seq_output_layer_idx: 2

  seq_output_seq_input_name: 'fasta'
  seq_output_seq_input: [
  # 'NCC=CC1=CN(C2CC(O)C(CO)O2)C(=O)NC1=O'
  # 'CCC=CC1=CN(C2CC(O)C(CO)O2)C(=O)NC1=O'
  # 'CSC=CC1=CN(C2CC(O)C(CO)O2)C(=O)NC1=O'
  'ABCDEFGHIJKLMNOPQRSTSUVWYZMRLLGVLLCLVTGPHGVLSQVQLQESGPDLLKPSETLCLTCKVTGFSITASGYYWSWIRQSQGKSPEWMGYISYSGSTAYSPSLQRRISISRDMAKNEFSLCLNSVTPEDTAVYYCARYTVICYNWEHRHKPPCRENHNQQAARCTHWCREPT'
  # 'AAAAABBBBBCCCCCDDDDDEEEEEFFFFFGGGGGHHHHHIIIIIJJJJJKKKKKLLLLLMMMMMNNNNNOOOOOPPPPPQQQQQRRRRRSSSSSTTTTTUUUUUVVVVVWWWWWYYYYYZZZZZ'
  # 'MRLLGVLLCLVTGPHGVLSQVQLQESGPDLLKPSETLCLTCKVTGFSITASGYYWSWIRQSQGKSPEXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
  ]
