# Local configuration

# Experiments to run

experiments: ['local/experiments/wide_features_valid/rnn_molweight_rdkit_maccs.yml']
model: 'rnn'

# Persistence of models
persistence:
  model: true

plots:
  print_train_test_pred: false
  print_train_test_pred_cnt: 15