# Local configuration

# Experiments to run

experiments: ['local/experiments/edge_property_prediction/rnn_edge_stitch.yml']

model: 'rnn'

# Persistence of models
persistence:
  model: false

plots:
  print_train_test_pred: true
  print_train_test_pred_cnt: 15