# Common configuration for everyone

# Database
db:
  user: 'postgres'
  pass: 'samurai'
  host: '192.168.201.207'
  name: 'chembl_21'

# Statistics
statistics:
  table: 'output.journal'

# Plots
plots:
  dir: 'local/plots'

experiments: ~
