# Common configuration for everyone

# Database
db:
  user: 'postgres'
  pass: 'samurai'
  host: 'asgard.kessl.net'
  name: 'chembl_21'
  driver: 'postgresql'

# Statistics
statistics:
  table: 'output.journal'

# Plots
plots:
  dir: 'local/plots'
  histograms: false
  histograms_dir: 'local/plots/hists'
  layer_activations: false
  layer_activations_dir: 'local/plots/activations'
  layer_activations_points_cap: 1000
  layer_activations_label_cap: 10

  seq_output: false
  seq_output_dir: 'local/plots/seq_output'
  seq_output_name: 'seq_output.png'
  seq_output_select_neurons: ~
  seq_output_ignore_neurons: ~
  seq_output_layer_idx: ~
  seq_output_seq_input_name: ~
  seq_output_seq_input: ~

  print_pred: false

  print_train_test_pred: false
  print_train_test_pred_cnt: 5

model: 'rnn'
grid: false

# Persistence of models
persistence:
  model: true
  model_dir: 'local/models'

experiments: ~
