# Common configuration for everyone

# Run
run:
  source: 'chembl'

# Database
db:
  user: 'guest'
  pass: 'relational'
  host: 'relational.fit.cvut.cz'
  name: 'ctu_qsar'

# Statistics
statistics:
  table: 'journal'

experiments: []
