# Common configuration for everyone

# Database
db:
  user: 'guest'
  pass: 'relational'
  host: 'relational.fit.cvut.cz'
  name: 'ctu_qsar'

# Statistics
statistics:
  table: 'journal'

# Plots
plots:
  dir: 'local/plots'

experiments: []
