# Common configuration for everyone

# Database
db:
  user: 'postgres'
  pass: 'samurai'
  host: '147.32.233.145'
  name: 'chembl_21'
  driver: 'postgresql'

# Statistics
statistics:
  table: 'output.journal'

# Plots
plots:
  dir: 'local/plots'
  histograms: false
  histograms_dir: 'local/plots/hists'
  layer_activations: false
  layer_activations_dir: 'local/plots/activations'
  layer_activations_points_cap: 1000
  layer_activations_label_cap: 10

# Persistence of models
persistence:
  model: true
  model_dir: 'local/models'

experiments: ~
