# Common configuration for everyone

# Database
db:
  user: 'postgres'
  pass: 'samurai'
  host: '10.203.103.29'
  name: 'chembl_21'
  driver: 'postgresql'

# Statistics
statistics:
  table: 'output.journal'

# Plots
plots:
  dir: 'local/plots'
  histograms: 'local/plots/hists'

experiments: ~
