# Default config containing all the default values for every setting

# Run
run:
  source: 'chembl'

# Database
db:
  user: 'guest'
  pass: 'relational'
  host: 'relational.fit.cvut.cz'
  name: 'ctu_qsar'

# Data fetching
fetch:
  table: 'target_molweight_1000'
  cols: ['canonical_smiles']
  index_col: ~
  limit: ~
  where: ~