# Default config containing all the default values for every setting

# Run
run:
  source: 'chembl'

# Database
db:
  user: 'guest'
  pass: 'relational'
  host: 'relational.fit.cvut.cz'
  name: 'ctu_qsar'

# Experiment setup to use
experiment: 'default'

# Experiment setups
experiment_setups:
  default:
    fetch: 'default'
    params: 'default'

# Fetch setups
fetch_setups:
  default:
    table: 'target_molweight_1000'
    cols: ['canonical_smiles']
    index_col: ~
    limit: ~
    where: ~

# Params setups
params_setups:
  default: ~